export enum AuditEventType {
  ATTEMPTED = "ATTEMPTED",
  RESERVED = "RESERVED",
  REJECTED_DUPLICATE = "REJECTED_DUPLICATE",
  REJECTED_SOLD_OUT = "REJECTED_SOLD_OUT",
  REJECTED_NOT_ACTIVE = "REJECTED_NOT_ACTIVE",
  CONFIRMED = "CONFIRMED",
  FAILED_DB = "FAILED_DB",
  ADMIN_RESET = "ADMIN_RESET",
}
